### ISSUE TITLE
Does this this still work with Lorex 2K doorbells?

### ISSUE THREAD

**Issue by esand** [baudneo/dahuavto2mqtt#1]
Trying to get anything working with a Lorex 2K doorbell (fw 1.000.010000000.8.R.20220903) and I tried this container from an HA thread. Building seems OK, but upon startup, it seems to error out and bootloops.

**Comment by baudneo** [comment]
Can u post the log output please. I have it running here and working fine for a lorex 2k doorbell. 

Edit: sorry for late reply, I didn't see any emails from GitHub about this, I came here from the notification dashboard.

**Comment by esand** [comment]
No worries about waiting for the reply.

Here's the output I get from building the container from what you've got in master. I tried with debugging flags on and off, both basically the same:

```
Traceback (most recent call last):
  File "/app/DahuaVTO.py", line 39, in <module>
'04/02/24 15:22:46.0313' INFO MQTTClient:19 -> MQTT_DEBUG=False
'04/02/24 15:22:46.0313' INFO MQTTClient:29 -> Set INFO level for clients.MQTTClient
    manager = DahuaVTOManager()
              ^^^^^^^^^^^^^^^^^
  File "/app/DahuaVTO.py", line 13, in __init__
    self._mqtt_client = MQTTClient()
                        ^^^^^^^^^^^^
  File "/app/clients/MQTTClient.py", line 32, in __init__
    self._mqtt_client = mqtt.Client(self._mqtt_config.client_id, clean_session=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/paho/mqtt/client.py", line 766, in __init__
    raise ValueError(
ValueError: Unsupported callback API version: version 2.0 added a callback_api_version, see migrations.md for details
'04/02/24 15:22:49.0017' INFO MQTTClient:19 -> MQTT_DEBUG=False
'04/02/24 15:22:49.0017' INFO MQTTClient:29 -> Set INFO level for clients.MQTTClient
```

**Comment by baudneo** [comment]
Paho lib needs to be pinned to a version from 3 or 4 month ago. The new paho lib apparently has breaking changes to the API.

**Comment by esand** [comment]
Would it be safe to say that at least for now, changing the requirements.txt file so that your paho-mqtt line is "paho-mqtt<2" so that it grabs the latest release prior to version 2.0.0 (which would be 1.6.1)?

I was taking a look at the breaking changes announcement for paho and I might try to take a stab at updating this repo code to work with 2.0. I have no Python experience though but hopefully it's somewhat trivial. If it works out, I'll send a pull request your way.

**Comment by baudneo** [comment]
Yes that should work. Pinning it for now will get things working. 

I can also update the code to work with paho 2+. This is a fork of the original repo, I hadn't pinned anything from the old stuff.

**Comment by esand** [comment]
Ok, sounds good. I'm going to fork this myself just for now to try the requirements.txt idea.

Also, aware this is a fork of the original. I've been trying to just find anything that'll work with this doorbell just so I can get an MQTT event of a doorbell press. First one wins 😄

**Comment by esand** [comment]
Going to close this issue, as I just confirmed that limiting paho-mqtt to pre v2.0.0 fixes the issue and I've submitted pull request #2

**Comment by baudneo** [comment]
Awesome, thank you for the PR!
